### ISSUE TITLE
Share load age structure data?

### ISSUE THREAD

**Issue by wilsongis** [p-j-r/covid-19#5]
I am looking at your model. I would like to see if I can reproduce. Can you share your "load age structure data"?

Thanks,
Mike

**Comment by p-j-r** [comment]
Hi Mike!
I'm guessing that you are working on the [SIR_model_India.py](https://github.com/p-j-r/covid-19/blob/master/SIR_model_India.py) code. The code is a simplified version of the pyRoss implementation and can be modified for any other nation, by changing the sheet name. Here's the [data](https://github.com/p-j-r/pyross/tree/master/examples/data) you want. Happy working on it!

**Comment by wilsongis** [comment]
Thanks I appreciate it. I am going to try applying the code to a University rather than a nation. I am curious if it will work. I appreciate both your help and your code.

**Comment by p-j-r** [comment]
Definitely, do share the code too!
